# This workflow will update discoveries.md with new discoveries from the feed.

name: Python application

on:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Discoveries Markdown
      run: |
        python extract_discoveries.py --markdown > discoveries.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Discoveries
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        commit_author: GitHub Actions <actions@github.com> 
